### ISSUE TITLE
native build: small change in Readme need it

### ISSUE THREAD

**Issue by kas1e** [AmigaLabs/binutils-gdb#15]
Configuring line should be :

`CFLAGS="-Wno-sign-compare" LDFLAGS="-lunix" ../configure --disable-gdb --disable-plugins --disable-nls --host=ppc-amigaos --target=ppc-amigaos --prefix=/os4_native`

**Comment by kas1e** [comment]
@migthymax 
I see you change readme a bit, but its a bit wrong, LDFLAG missing

**Comment by migthymax** [comment]
See updated README.MD

**Comment by kas1e** [comment]
@migthymax 
Nope, it still wrong : you removed CFLAGS and forget to add LFLAGS. I will try to do it myself now if repo give me access to
