### ISSUE TITLE
native build: ../../../gnulib/import/getprogname.c:291:4: error: #error "getprogname module not ported to this OS"

### ISSUE THREAD

**Issue by kas1e** [AmigaLabs/binutils-gdb#17]
After build process done with most of binutils, as, ld and co, it tries to build gnulib, and in the file getprograname.c fail because we don't have there necessary getprogname() implementation.

Checking old adtools, fine out that it also have the same getprogname.c file , without any changes, so dunno how it builds (and if at all), if it's only clib4 to day have getprogname() implementation, and before not clib2 not newlib has it. Maybe adtools just didn't build gnulib ?

**Comment by migthymax** [comment]
Can you check if that is still present when building cross tools and native tools. For native tools be sure to use latest beta10 clib4 branch.

**Comment by kas1e** [comment]
@migthymax 
Yes, that one fixed for sure

**Comment by kas1e** [comment]
Fixed
