### ISSUE TITLE
[GDB] Warning: Couldn't determine a path for the index cache directory

### ISSUE THREAD

**Issue by kas1e** [AmigaLabs/binutils-gdb#26]
This is a warning are known issue : The reason is because there the HOME environment variable is set.
If you do this before running gdb the warning is no longer shown: `setenv HOME=aaaa`

So that mean that inside of GDB we need to deal with HOME (replaced it to PROGDIR:) for amigaos4 , such we will have no such warning , and the HOME will be as always for all amigaos4 apps as "PROGDIR:". 

Usually i do it like:

```C
#ifdef __amigaos4__
HOME="PROGDIR:";
#else
what were originally for unix
#endif
```

**Comment by migthymax** [comment]
Just for information proposes, the location fo the cache can be shown with the following gdb command `show index-cache`

**Comment by kas1e** [comment]
Fixed ! Thanks !
